name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
